name: Build

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  run:
    name: Go install
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      
      - name: Lint code
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0 && 
          golangci-lint run --skip-dirs=cmd

      - name: Test code
        run: go test .
